# Explore your data file some more
- We are continuing (from Colab 12) our work on data exploring using pandas.

In [1]:
### Import package(s)
import pandas as pd

In [2]:
csvFile = 'https://raw.githubusercontent.com/csbfx/advpy122-data/master/top_movies_2020.csv'

movies = pd.read_csv(csvFile)
movies.head()

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965
3          E.T. the Extra-Terrestrial  435110554        1329174791  1982
4                             Titanic  659363944        1270101626  1997

## Filtering DataFrame with string datatype
You can search for instances of a substring in a column using str.contains(), `df[colname].str.contain(<str>)`. The method will return table that meets the condition. If you want to return a single column you can define which column to print `df[df[colname].str.contain(<str>)][colname2]`.

### Series to list
To convert a Series to a list use `series.tolist()`

In [8]:
### You can search for instances of a substring in a column and return rows
## Search for substring (str.contains) and return the table
movies[movies['Title'].str.contains("man")]

## You can print just the column 'Title'
movies[movies['Title'].str.contains("man")][['Title']]
## To convert this Series to a list use series.tolist()
man_list = movies[movies['Title'].str.contains("man")]['Title'].tolist()
man_list

['The Ten Commandments',
 'Batman',
 'Superman',
 'Wonder Woman',
 'Jumanji: Welcome to the Jungle',
 'An Officer and a Gentleman',
 'Batman Forever',
 'Pretty Woman']

### Working with the list
Once you have the list, how do you:
1. How to find out how many elements there are in your list?  
2. How to get the first 5 elements in the list?

In [12]:
### To retrieve the number of elements in the list use len()
len(man_list)
### To retrieve the first 5 elements of the list, use a slice
slice = man_list[:5]
slice

['The Ten Commandments',
 'Batman',
 'Superman',
 'Wonder Woman',
 'Jumanji: Welcome to the Jungle']

### Finding unique values
We can retrieve unique values to ask:
1. How many times an item occurs in a column?
2. To extract out distinct observation elements in a column
3. To count the number of distinct observations in a column

In [13]:
### To count the number of times a unique item is found in a column we can use value_count()
value_counts = movies['Year'].value_counts()
value_counts
### To extract out the unique values in a column using the unique() method

### To quantify how many unique using the nunique() method

Year
2016    7
2019    7
2015    6
2004    6
2017    5
       ..
1976    1
1952    1
1921    1
1988    1
1979    1
Name: count, Length: 74, dtype: int64

### Question 13.1: How many distinct movies came out in the 1990s?
To find the number of distinct movies during these years:
1. Filter out the DataFrame based on conditions of the year
2. Get the length `len()` (number of rows) of your filtered DataFrame
  
-or-   
1. Use the str approach to find all years in 1990s (ie., "199")

In [15]:
### Filter out the DataFrame based on conditions of the year combine with len
### Your code
len(movies[(movies['Year'] >= 1990) & (movies['Year'] <= 1999)])

29

In [16]:
### Use the str approach to find all years in 1990s
movies[movies['Year'].astype(str).str.contains("199")]

,Title,Gross,Gross (Adjusted),Year
4,Titanic,659363944,1270101626,1997
17,Jurassic Park,404214720,860163189,1993
18,Star Wars: Episode I - The Phantom Menace,474544677,846224377,1999
19,The Lion King,422783777,835301768,1994
25,Forrest Gump,330455270,736829627,1994
41,Independence Day,306169268,649049593,1996
42,Home Alone,285761243,634669454,1990
73,The Sixth Sense,293506292,539516167,1999
90,Twister,241721524,512427497,1996
91,Men in Black,250690539,511758479,1997
102,Mrs. Doubtfire,219195243,493652828,1993
103,Aladdin,217350219,491384351,1992
104,Ghost,217631306,482228924,1990
112,The Lost World: Jurassic Park,229086679,467656700,1997
118,Terminator 2: Judgment Day,205881154,456999262,1991
124,Toy Story,222498679,448849236,1995
125,Toy Story 2,245852179,448228005,1999
137,Saving Private Ryan,217049603,429179732,1998
142,Beauty and the Beast,218967620,425057869,1991
146,The Fugitive,183875760,416002701,1993
154,Dances with Wolves,184208848,409462441,1990
163,Armageddon,201578182,402726348,1998
169,Batman Forever,184069126,396446574,1995
171,Pretty Woman,178406268,395192868,1990
176,Home Alone 2: Lost in New York,173585516,392130752,1992
182,Mission: Impossible,180981856,383664957,1996
188,Austin Powers: The Spy Who Shagged Me,206040086,380038767,1999
194,Apollo 13,173837933,373466649,1995
199,Liar Liar,181410615,370330510,1997

### Question 13.2: How many distinct movies came out for each decade?
Can you write a for loop to iterate through all the decades?

In [19]:
decades = ['191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202']

for decade_prefix in decades:
    decade_movies = movies[movies['Year'].astype(str).str.startswith(decade_prefix)]
    print(f"Decade {decade_prefix}0s: {len(decade_movies)} distinct movies")

Decade 1910s: 0 distinct movies
Decade 1920s: 1 distinct movies
Decade 1930s: 2 distinct movies
Decade 1940s: 7 distinct movies
Decade 1950s: 13 distinct movies
Decade 1960s: 19 distinct movies
Decade 1970s: 25 distinct movies
Decade 1980s: 21 distinct movies
Decade 1990s: 29 distinct movies
Decade 2000s: 39 distinct movies
Decade 2010s: 44 distinct movies
Decade 2020s: 0 distinct movies

In [ ]:
# decades=['191','192','193','194','195','196','197','198','199','200','201','202']

### Working with string elements
We can think of string as a list of elements. In a column with string datatype, we can split the string `str` using the `split()` method.

In [ ]:
### The split method takes a string and split it into a list


## To extract the first element and place it into a new column, assign the new column and run split and extract first element

,Title,Gross,Gross (Adjusted),Year,first_word
0,Gone with the Wind,200852579,1895421694,1939,Gone
1,Star Wars: Episode IV - A New Hope,460998507,1668979715,1977,Star
2,The Sound of Music,159287539,1335086324,1965,The
3,E.T. the Extra-Terrestrial,435110554,1329174791,1982,E.T.
4,Titanic,659363944,1270101626,1997,Titanic
...,...,...,...,...,...
195,Patton,61749765,373287682,1970,Patton
196,Fatal Attraction,156645693,371808159,1987,Fatal
197,Iron Man 2,312433331,371691971,2010,Iron
198,Zootopia,341268248,371109157,2016,Zootopia
199,Liar Liar,181410615,370330510,1997,Liar

### Question 13.3: Can you extract the last element of title
To extract the last element and place it into a new column, 'last word'

In [21]:
movies['last'] = movies.Title.str.split().str[-1]
movies.head()

,Title,Gross,Gross (Adjusted),Year,last
0,Gone with the Wind,200852579,1895421694,1939,Wind
1,Star Wars: Episode IV - A New Hope,460998507,1668979715,1977,Hope
2,The Sound of Music,159287539,1335086324,1965,Music
3,E.T. the Extra-Terrestrial,435110554,1329174791,1982,Extra-Terrestrial
4,Titanic,659363944,1270101626,1997,Titanic